version: 1
release_posture:
  mode: public-preview-human-orchestrated
  summary: 'Phase B approved (2026-02-14). Implementation underway for F0001 (Dashboard)
    and F0002 (Broker Relationship Management). CI enforces strict infra and security
    gates at this stage.

    '
current_stage: implementation
implementation_scope:
  active_feature: F0001-dashboard, F0002-broker-relationship-management
  active_stories:
  - F0001-S0001
  - F0001-S0002
  - F0001-S0003
  - F0001-S0004
  - F0001-S0005
  - F0002-S0001
  - F0002-S0002
  - F0002-S0003
  - F0002-S0004
  - F0002-S0005
  - F0002-S0006
  - F0002-S0007
  note: "Implementation scope includes F0001 dashboard slice, F0002 broker relationship\
    \ management stories S0001\u2013S0007 for Broker 360, contacts, and timeline."
stages:
  framework-bootstrap:
    description: Framework scaffolding phase before solution implementation starts
      (active stage for the initial public preview).
    required_gates:
    - boundary_genericness
    - skill_regression
    - infra_non_strict
  planning:
    description: Planning artifacts are being authored; implementation remains placeholder.
    required_gates:
    - boundary_genericness
    - api_contract
    - solution_contract
    - infra_non_strict
    - security_planning_light
  implementation:
    description: Application code/runtime is being built; strict operational/security
      gates apply.
    required_gates:
    - boundary_genericness
    - api_contract
    - solution_contract
    - infra_strict
    - security_planning_strict
  release-readiness:
    description: Public release hardening stage with strict gates and review evidence.
    required_gates:
    - boundary_genericness
    - api_contract
    - solution_contract
    - infra_strict
    - security_planning_strict
gates:
  boundary_genericness:
    description: Prevent solution-specific leakage into generic framework agents.
    command:
    - python3
    - scripts/validate-genericness.py
  skill_regression:
    description: Validate skill metadata, structure quality, and routing regressions.
    command:
    - python3
    - scripts/run-skill-regression.py
  api_contract:
    description: Validate OpenAPI structural and canonical error-contract rules.
    command:
    - python3
    - agents/architect/scripts/validate-api-contract.py
    - planning-mds/api/nebula-api.yaml
  solution_contract:
    description: Validate solution-specific story/API contract alignment.
    command:
    - python3
    - planning-mds/testing/validate-nebula-api-contract.py
    - planning-mds/api/nebula-api.yaml
  infra_non_strict:
    description: Informational infrastructure baseline checks during bootstrap/planning.
    command:
    - python3
    - agents/devops/scripts/validate-infrastructure.py
    - .
  infra_strict:
    description: Strict infrastructure gate for implementation/release stages.
    command:
    - python3
    - agents/devops/scripts/validate-infrastructure.py
    - .
    - --strict
  security_planning_light:
    description: Ensure required security planning artifacts exist.
    command:
    - python3
    - agents/security/scripts/security-audit.py
    - planning-mds/security
  security_planning_strict:
    description: Enforce non-draft security artifacts and dated review evidence.
    command:
    - python3
    - agents/security/scripts/security-audit.py
    - planning-mds/security
    - --strict
