namespace Nebula.Application.DTOs;

public record RenewalDto(
    Guid Id,
    Guid AccountId,
    Guid BrokerId,
    Guid PolicyId,
    string? LineOfBusiness,
    string CurrentStatus,
    DateTime PolicyExpirationDate,
    DateTime TargetOutreachDate,
    Guid AssignedToUserId,
    string? LostReasonCode,
    string? LostReasonDetail,
    Guid? BoundPolicyId,
    Guid? RenewalSubmissionId,
    string? Urgency,
    IReadOnlyList<string> AvailableTransitions,
    string? AssignedUserDisplayName,
    string? AccountName,
    string? BrokerName,
    string RowVersion,
    DateTime CreatedAt,
    Guid CreatedByUserId,
    DateTime UpdatedAt,
    Guid UpdatedByUserId);
